on:
    push:
      branches:
        - main

permissions:
    contents: write
    pull-requests: write
  
name: release-please


jobs:
    lint:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest
    
        ############################################
        # Grant status permission for MULTI_STATUS #
        ############################################
        permissions:
          contents: read
          packages: read
          statuses: write
    
        ##################
        # Load all steps #
        ##################
        steps:
          ##########################
          # Checkout the code base #
          ##########################
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
              # Full git history is needed to get a proper
              # list of changed files within `super-linter`
              fetch-depth: 0
        
          # Get enviroment variables (linter config) from .github/super-linter.env
          - run: cat .github/super-linter.env >> "$GITHUB_ENV"

          ################################
          # Run Linter against code base #
          ################################
          - name: Lint Code Base
            uses: super-linter/super-linter@v5
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    release-please:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - uses: google-github-actions/release-please-action@v3
          with:
            release-type: node
            package-name: mypackage
